import math

TOTAL_FIELD_LENGTH = 105
TOTAL_FIELD_WIDTH = 68
GOAL_POST_WIDTH = 7.32
PENALTY_BOX_LENGTH = 16.5
PENALTY_BOX_WIDTH = 40.2
CENTER_CIRCLE_RADIUS = 9.5
AVERAGE_PLAYER_HEIGHT = 1.8
PENALTY_SPOT_DISTANCE = 11
PENALTY_ARC_RADIUS = 9.15
HALF_WIDTH = TOTAL_FIELD_WIDTH / 2
HALF_LENGTH = TOTAL_FIELD_LENGTH / 2
BOX_TO_FLAG = (TOTAL_FIELD_WIDTH - PENALTY_BOX_WIDTH) / 2
BOX_TO_FLAG_2 = ((TOTAL_FIELD_WIDTH - PENALTY_BOX_WIDTH) / 2) + PENALTY_BOX_WIDTH
CHORD_VERTICAL_DISTANCE = PENALTY_BOX_LENGTH - PENALTY_SPOT_DISTANCE
CHORD_LENGTH = 2 * math.sqrt((PENALTY_ARC_RADIUS)**2 - (CHORD_VERTICAL_DISTANCE)**2)
HALF_BOX = PENALTY_BOX_LENGTH /2
HALF_CHORD_LENGTH = CHORD_LENGTH / 2
BOX_EDGE_TO_POINT = HALF_WIDTH - HALF_CHORD_LENGTH
BOX_EDGE_TO_POINT_2 = HALF_WIDTH + HALF_CHORD_LENGTH
EDGE_TO_OTHER_BOX = TOTAL_FIELD_LENGTH - PENALTY_BOX_LENGTH
HALF_POST = GOAL_POST_WIDTH / 2
POST_EDGE = HALF_WIDTH - HALF_POST
POST_EDGE_2 = HALF_WIDTH + HALF_POST
CENTER_CIRCLE_POINT = HALF_WIDTH - CENTER_CIRCLE_RADIUS
CENTER_CIRCLE_POINT_2 = HALF_WIDTH + CENTER_CIRCLE_RADIUS 